-- =====================================================================
--  QUESTIONS DU TEST PPA (serveur uniquement : les réponses ne sont jamais envoyées aux joueurs)
-- =====================================================================
-- Questions du test. kind = 'question' (connaissance) ou 'situation' (mise en situation).
-- correct = numéro de la bonne réponse (1, 2, 3 ou 4). Les réponses sont mélangées à l'affichage.
Config.Questions = {
    civil = {
        { kind = 'question', text = 'Le PPA civil autorise le port de quelle catégorie d\'arme ?',
          answers = { 'Pistolet', 'Fusil d\'assaut', 'Toutes les armes', 'Armes lourdes' }, correct = 1 },
        { kind = 'question', text = 'Où devez-vous ranger votre arme lorsque vous ne l\'utilisez pas ?',
          answers = { 'Dans son étui ou à la ceinture, sécurisée', 'Dans la main, prête à tirer', 'Sur le siège passager', 'Peu importe' }, correct = 1 },
        { kind = 'question', text = 'Pouvez-vous porter votre arme sous l\'emprise de l\'alcool ?',
          answers = { 'Non, jamais', 'Oui, si je ne conduis pas', 'Oui, avec modération', 'Oui, la nuit seulement' }, correct = 1 },
        { kind = 'question', text = 'Que devez-vous présenter si un policier vous contrôle armé ?',
          answers = { 'Mon PPA et ma carte d\'identité', 'Rien du tout', 'Seulement mon permis de conduire', 'Ma facture d\'achat' }, correct = 1 },
        { kind = 'question', text = 'Le PPA peut-il être prêté à une autre personne ?',
          answers = { 'Non, il est strictement personnel', 'Oui, à un membre de la famille', 'Oui, pour une journée', 'Oui, contre paiement' }, correct = 1 },
        { kind = 'question', text = 'Dans quel cas l\'usage de votre arme est-il légal ?',
          answers = { 'Légitime défense, face à une menace immédiate et proportionnée', 'Pour impressionner quelqu\'un', 'Pour régler un différend', 'Dès qu\'on m\'insulte' }, correct = 1 },
        { kind = 'situation', text = 'Un individu vous insulte violemment dans la rue mais ne vous menace d\'aucune arme. Que faites-vous ?',
          answers = { 'Je m\'éloigne et j\'appelle la police si besoin', 'Je sors mon arme pour lui faire peur', 'Je tire en l\'air', 'Je le poursuis' }, correct = 1 },
        { kind = 'situation', text = 'Un policier vous demande de lever les mains alors que vous êtes armé. Que faites-vous ?',
          answers = { 'Je lève les mains, je signale calmement mon arme et mon PPA', 'Je sors mon PPA rapidement de ma poche', 'Je m\'enfuis', 'Je pose la main sur mon arme pour la montrer' }, correct = 1 },
        { kind = 'situation', text = 'Vous voyez un braquage en cours dans une supérette. Que faites-vous ?',
          answers = { 'Je me mets à l\'abri et j\'appelle la police', 'J\'entre et j\'ouvre le feu', 'Je tire sur la voiture des braqueurs', 'Je filme sans me cacher' }, correct = 1 },
        { kind = 'situation', text = 'Un ami vous demande de lui prêter votre arme pour « se protéger ». Que répondez-vous ?',
          answers = { 'Je refuse : l\'arme et le PPA sont personnels', 'J\'accepte pour une soirée', 'J\'accepte s\'il me paie', 'J\'accepte s\'il a un permis de conduire' }, correct = 1 },
        { kind = 'situation', text = 'Quelqu\'un pointe une arme sur vous et exige votre portefeuille. Quelle est la meilleure réaction ?',
          answers = { 'Donner le portefeuille et préserver sa vie, puis prévenir la police', 'Dégainer immédiatement', 'Se jeter sur lui', 'Crier pour attirer du monde' }, correct = 1 },
        { kind = 'question', text = 'Que se passe-t-il quand votre PPA a expiré ?',
          answers = { 'Je dois repasser la visite médicale avant de porter une arme', 'Rien, il reste valable', 'Il se renouvelle tout seul', 'Je peux porter une arme une semaine de plus' }, correct = 1 },
    },
    fdo = {
        { kind = 'question', text = 'Quelles catégories d\'armes autorise le PPA forces de l\'ordre ?',
          answers = { 'Armes légères et armes lourdes', 'Pistolet uniquement', 'Aucune arme', 'Armes blanches uniquement' }, correct = 1 },
        { kind = 'question', text = 'Quel principe encadre tout usage de la force ?',
          answers = { 'Nécessité et proportionnalité', 'Rapidité avant tout', 'Intimidation', 'Le grade le plus élevé décide seul' }, correct = 1 },
        { kind = 'question', text = 'Une arme lourde peut être sortie…',
          answers = { 'Sur une intervention qui le justifie, avec l\'accord de la hiérarchie', 'À tout moment en patrouille', 'Pour les contrôles routiers', 'Hors service' }, correct = 1 },
        { kind = 'question', text = 'Hors service, que faites-vous de votre arme de service ?',
          answers = { 'Je la range à l\'armurerie du poste', 'Je la garde sur moi en civil', 'Je la prête à un collègue', 'Je la laisse dans ma voiture' }, correct = 1 },
        { kind = 'question', text = 'Avant d\'ouvrir le feu, sauf danger immédiat, vous devez…',
          answers = { 'Faire des sommations claires', 'Tirer un coup de semonce sur la personne', 'Attendre que le suspect tire', 'Rien de particulier' }, correct = 1 },
        { kind = 'situation', text = 'Un suspect s\'enfuit à pied, sans arme visible, après un vol simple. Que faites-vous ?',
          answers = { 'Je le poursuis sans faire usage de mon arme', 'Je tire dans les jambes', 'Je tire dans son dos', 'J\'abandonne immédiatement' }, correct = 1 },
        { kind = 'situation', text = 'Un individu armé retient un otage et menace de tirer. Quelle est la priorité ?',
          answers = { 'Sécuriser la zone, négocier et attendre les renforts', 'Foncer seul pour le neutraliser', 'Tirer immédiatement malgré l\'otage', 'Quitter les lieux' }, correct = 1 },
        { kind = 'situation', text = 'Lors d\'un contrôle, le conducteur sort lentement ses papiers et reste calme. Votre arme…',
          answers = { 'Reste dans son étui, je reste vigilant', 'Est pointée sur lui en permanence', 'Est posée sur le capot', 'Est donnée au collègue' }, correct = 1 },
        { kind = 'situation', text = 'Une fusillade éclate et un collègue est blessé. Que faites-vous en premier ?',
          answers = { 'Me mettre à couvert, demander des renforts et des secours', 'Courir au milieu de la rue pour l\'aider', 'Vider mon chargeur au hasard', 'Prendre une photo de la scène' }, correct = 1 },
        { kind = 'situation', text = 'Un civil armé et titulaire d\'un PPA est contrôlé et coopère. Que faites-vous ?',
          answers = { 'Je vérifie son PPA et son identité, puis je le laisse repartir si tout est en règle', 'Je confisque l\'arme sans raison', 'Je l\'arrête automatiquement', 'Je l\'ignore' }, correct = 1 },
    },
}
