/* =========================================================
   CATALOGUE DE L'ÉDITEUR DE MAP
   Props et personnages proposés dans le menu, rangés par catégorie
   (ordre alphabétique automatique dans chaque catégorie).

   Tu peux ajouter tes propres modèles, y compris des props ajoutés
   par une ressource (MLO, packs) : ajoute simplement le nom du modèle
   dans la bonne catégorie, ou crée une nouvelle catégorie.

   Images d'aperçu au survol :
   - personnages : documentation officielle FiveM
   - props : site gta-objects.xyz (si une image manque, le bouton
     « Voir en 3D » montre l'objet directement en jeu)
   ========================================================= */
window.CATALOG = {
    pedImage: 'https://docs.fivem.net/peds/{name}.webp',
    propImage: 'https://gta-objects.xyz/gallery/objects/{name}.jpg',
    props: [
    {
        "cat": "Bancs, tables et chaises",
        "icon": "🪑",
        "items": [
            "prop_beach_lounger",
            "prop_bench_01a",
            "prop_bench_01b",
            "prop_bench_01c",
            "prop_bench_02",
            "prop_bench_03",
            "prop_bench_04",
            "prop_bench_05",
            "prop_bench_06",
            "prop_bench_07",
            "prop_bench_08",
            "prop_bench_09",
            "prop_bench_10",
            "prop_bench_11",
            "prop_chair_01a",
            "prop_chair_01b",
            "prop_chair_02",
            "prop_chair_03",
            "prop_chair_04a",
            "prop_chair_04b",
            "prop_chair_05",
            "prop_chair_06",
            "prop_chair_07",
            "prop_chair_08",
            "prop_chair_09",
            "prop_chair_10",
            "prop_gazebo_01",
            "prop_gazebo_02",
            "prop_gazebo_03",
            "prop_off_chair_01",
            "prop_off_chair_03",
            "prop_off_chair_04",
            "prop_off_chair_05",
            "prop_parasol_01",
            "prop_parasol_02",
            "prop_parasol_03",
            "prop_patio_lounger1",
            "prop_picnictable_01",
            "prop_picnictable_02",
            "prop_skid_chair_01",
            "prop_table_01",
            "prop_table_02",
            "prop_table_03",
            "prop_table_04",
            "prop_table_05",
            "prop_table_06",
            "prop_table_07",
            "prop_table_08"
        ]
    },
    {
        "cat": "Canapés et intérieur",
        "icon": "🛋️",
        "items": [
            "prop_bar_fridge_01",
            "prop_coffee_mac_02",
            "prop_cooker_03",
            "prop_couch_01",
            "prop_couch_03",
            "prop_couch_04",
            "prop_fridge_01",
            "prop_fridge_03",
            "prop_ld_farm_couch01",
            "prop_ld_farm_couch02",
            "prop_microwave_1",
            "prop_plant_int_01a",
            "prop_plant_int_01b",
            "prop_plant_int_02a",
            "prop_plant_int_03a",
            "prop_rub_couch01",
            "prop_rub_couch02",
            "prop_rub_couch03",
            "prop_rub_couch04",
            "prop_rub_matress_01",
            "prop_tv_03",
            "prop_tv_06",
            "prop_tv_flat_01",
            "prop_tv_flat_02"
        ]
    },
    {
        "cat": "Chantier et barrières",
        "icon": "🚧",
        "items": [
            "prop_barrier_work01a",
            "prop_barrier_work02a",
            "prop_barrier_work04a",
            "prop_barrier_work05",
            "prop_barrier_work06a",
            "prop_cementbags01",
            "prop_cementmixer_01a",
            "prop_conc_blocks01a",
            "prop_consign_01a",
            "prop_consign_02a",
            "prop_fncconstruc_01d",
            "prop_fncconstruc_02a",
            "prop_fnclink_02a",
            "prop_fnclink_03a",
            "prop_mp_arrow_barrier_01",
            "prop_mp_barrier_01",
            "prop_mp_barrier_01b",
            "prop_mp_barrier_02",
            "prop_mp_barrier_02b",
            "prop_roadcone01a",
            "prop_roadcone01b",
            "prop_roadcone01c",
            "prop_roadcone02a",
            "prop_roadcone02b",
            "prop_roadcone02c",
            "prop_roadpole_01a",
            "prop_worklight_01a",
            "prop_worklight_02a",
            "prop_worklight_03a",
            "prop_worklight_03b",
            "prop_worklight_04a"
        ]
    },
    {
        "cat": "Caisses, palettes et conteneurs",
        "icon": "📦",
        "items": [
            "prop_box_ammo01a",
            "prop_box_ammo02a",
            "prop_box_ammo03a",
            "prop_box_ammo04a",
            "prop_box_ammo07a",
            "prop_box_wood01a",
            "prop_box_wood02a",
            "prop_box_wood03a",
            "prop_box_wood04a",
            "prop_box_wood05a",
            "prop_box_wood06a",
            "prop_box_wood07a",
            "prop_box_wood08a",
            "prop_boxpile_01a",
            "prop_boxpile_02b",
            "prop_boxpile_06a",
            "prop_container_01a",
            "prop_container_01b",
            "prop_container_02a",
            "prop_container_03a",
            "prop_container_04a",
            "prop_container_05a",
            "prop_container_old1",
            "prop_cratepile_07a",
            "prop_mil_crate_01",
            "prop_mil_crate_02",
            "prop_pallet_01a",
            "prop_pallet_02a",
            "prop_pallet_03a",
            "prop_pallet_03b",
            "prop_pallettruck_01"
        ]
    },
    {
        "cat": "Poubelles et déchets",
        "icon": "🗑️",
        "items": [
            "prop_bin_01a",
            "prop_bin_02a",
            "prop_bin_03a",
            "prop_bin_04a",
            "prop_bin_05a",
            "prop_bin_06a",
            "prop_bin_07a",
            "prop_bin_08a",
            "prop_bin_10a",
            "prop_bin_12a",
            "prop_bin_14a",
            "prop_dumpster_01a",
            "prop_dumpster_02a",
            "prop_dumpster_02b",
            "prop_dumpster_3a",
            "prop_dumpster_4a",
            "prop_dumpster_4b",
            "prop_rub_binbag_01",
            "prop_rub_binbag_03",
            "prop_rub_binbag_05",
            "prop_rub_binbag_sd_01"
        ]
    },
    {
        "cat": "Épaves et ferraille",
        "icon": "🚗",
        "items": [
            "prop_rub_carwreck_10",
            "prop_rub_carwreck_11",
            "prop_rub_carwreck_12",
            "prop_rub_carwreck_13",
            "prop_rub_carwreck_14",
            "prop_rub_carwreck_15",
            "prop_rub_carwreck_16",
            "prop_rub_carwreck_2",
            "prop_rub_carwreck_3",
            "prop_rub_carwreck_5",
            "prop_rub_carwreck_7",
            "prop_rub_carwreck_8",
            "prop_rub_carwreck_9",
            "prop_rub_scrap_02",
            "prop_rub_scrap_03",
            "prop_rub_scrap_04",
            "prop_rub_scrap_05",
            "prop_rub_scrap_06",
            "prop_rub_scrap_07",
            "prop_rub_tyre_01",
            "prop_rub_tyre_02",
            "prop_rub_tyre_03",
            "prop_tyre_wall_01"
        ]
    },
    {
        "cat": "Bidons, barils et gaz",
        "icon": "🛢️",
        "items": [
            "prop_barrel_01a",
            "prop_barrel_02a",
            "prop_barrel_02b",
            "prop_barrel_03a",
            "prop_barrel_exp_01a",
            "prop_gas_pump_1a",
            "prop_gas_pump_1b",
            "prop_gas_pump_1c",
            "prop_gas_pump_1d",
            "prop_gas_pump_old2",
            "prop_gascyl_01a",
            "prop_gascyl_02a",
            "prop_jerrycan_01a"
        ]
    },
    {
        "cat": "Distributeurs et rue",
        "icon": "🏧",
        "items": [
            "prop_atm_01",
            "prop_atm_02",
            "prop_atm_03",
            "prop_fire_hydrant_1",
            "prop_fire_hydrant_2",
            "prop_fleeca_atm",
            "prop_news_disp_02a",
            "prop_parknmeter_01",
            "prop_parknmeter_02",
            "prop_phonebox_01a",
            "prop_phonebox_04",
            "prop_postbox_01a",
            "prop_vend_coffe_01",
            "prop_vend_condom_01",
            "prop_vend_fags_01",
            "prop_vend_snak_01",
            "prop_vend_soda_01",
            "prop_vend_soda_02",
            "prop_vend_water_01",
            "prop_watercooler"
        ]
    },
    {
        "cat": "Électricité et éclairage",
        "icon": "💡",
        "items": [
            "prop_cctv_cam_01a",
            "prop_cctv_cam_02a",
            "prop_cctv_cam_04a",
            "prop_elecbox_01a",
            "prop_elecbox_02a",
            "prop_elecbox_03a",
            "prop_elecbox_10",
            "prop_generator_01a",
            "prop_generator_02a",
            "prop_generator_03a",
            "prop_generator_03b",
            "prop_generator_04",
            "prop_streetlight_01",
            "prop_streetlight_01b",
            "prop_streetlight_03",
            "prop_streetlight_09",
            "prop_telegraph_01a",
            "prop_telegraph_02a",
            "prop_traffic_01a",
            "prop_traffic_01b",
            "prop_traffic_01d",
            "prop_traffic_03a"
        ]
    },
    {
        "cat": "Panneaux et drapeaux",
        "icon": "🚩",
        "items": [
            "prop_flag_canada",
            "prop_flag_france",
            "prop_flag_mexico",
            "prop_flag_uk",
            "prop_flag_us",
            "prop_sign_road_01a",
            "prop_sign_road_02a",
            "prop_sign_road_03a",
            "prop_sign_road_04a",
            "prop_sign_road_05a",
            "prop_sign_road_06a",
            "prop_sign_road_restriction_10"
        ]
    },
    {
        "cat": "Ateliers et outils",
        "icon": "🛠️",
        "items": [
            "gr_prop_gr_bench_01a",
            "gr_prop_gr_bench_02a",
            "gr_prop_gr_bench_03a",
            "gr_prop_gr_bench_04a",
            "prop_carcreeper",
            "prop_carjack",
            "prop_engine_hoist",
            "prop_mp_ramp_01",
            "prop_mp_ramp_02",
            "prop_mp_ramp_03",
            "prop_tool_bench02",
            "prop_tool_bench02_ld",
            "prop_tool_box_01",
            "prop_tool_box_02",
            "prop_tool_box_04",
            "prop_toolchest_01",
            "prop_toolchest_02",
            "prop_toolchest_03",
            "prop_toolchest_04",
            "prop_toolchest_05"
        ]
    },
    {
        "cat": "Drogue et laboratoires",
        "icon": "⚗️",
        "items": [
            "bkr_prop_coke_block_01a",
            "bkr_prop_coke_table01a",
            "bkr_prop_meth_table01a",
            "bkr_prop_weed_lrg_01a",
            "bkr_prop_weed_med_01a",
            "bkr_prop_weed_table_01a",
            "h4_prop_bush_cocaplant_01",
            "prop_coke_block_01",
            "prop_drug_package",
            "prop_drug_package_02",
            "prop_stoneshroom1",
            "prop_stoneshroom2",
            "prop_weed_01",
            "prop_weed_02",
            "prop_weed_block_01",
            "prop_weed_bottle"
        ]
    },
    {
        "cat": "Bureau et électronique",
        "icon": "💻",
        "items": [
            "p_v_43_safe_s",
            "prop_fax_01",
            "prop_filecab_01",
            "prop_keyboard_01a",
            "prop_laptop_01a",
            "prop_laptop_lester",
            "prop_ld_int_safe_01",
            "prop_monitor_01a",
            "prop_monitor_02",
            "prop_off_phone_01",
            "prop_printer_01",
            "prop_printer_02",
            "prop_till_01",
            "prop_till_02"
        ]
    },
    {
        "cat": "Camping et extérieur",
        "icon": "⛺",
        "items": [
            "prop_bbq_1",
            "prop_bbq_2",
            "prop_bbq_3",
            "prop_bbq_4",
            "prop_bbq_5",
            "prop_beach_fire",
            "prop_haybale_01",
            "prop_haybale_02",
            "prop_haybale_03",
            "prop_haybale_stack_01",
            "prop_rock_1_a",
            "prop_rock_4_big",
            "prop_skid_sleepbag_1",
            "prop_skid_tent_01",
            "prop_skid_tent_01b",
            "prop_skid_tent_03"
        ]
    },
    {
        "cat": "Plantes et arbres",
        "icon": "🌳",
        "items": [
            "prop_bush_lrg_01",
            "prop_plant_01a",
            "prop_plant_01b",
            "prop_pot_plant_01a",
            "prop_pot_plant_02a",
            "prop_pot_plant_03a",
            "prop_pot_plant_04a",
            "prop_pot_plant_05a",
            "prop_tree_birch_01",
            "prop_tree_cedar_02",
            "prop_tree_jacada_01"
        ]
    },
    {
        "cat": "Sport, musique et loisirs",
        "icon": "🏀",
        "items": [
            "prop_arcade_01",
            "prop_barbell_01",
            "prop_basketball_net",
            "prop_beach_volball01",
            "prop_jukebox_01",
            "prop_jukebox_02",
            "prop_muscle_bench_01",
            "prop_muscle_bench_02",
            "prop_muscle_bench_03",
            "prop_muscle_bench_04",
            "prop_muscle_bench_05",
            "prop_muscle_bench_06",
            "prop_pooltable_02",
            "prop_pooltable_3b",
            "prop_speaker_01",
            "prop_speaker_05",
            "prop_speaker_06"
        ]
    },
    {
        "cat": "Stands et nourriture",
        "icon": "🌭",
        "items": [
            "prop_beer_box_01",
            "prop_burgerstand_01",
            "prop_food_van_01",
            "prop_food_van_02",
            "prop_hotdogstand_01"
        ]
    }
],
    peds: [
    {
        "cat": "Hommes (civils)",
        "icon": "🧑",
        "items": [
            "a_m_m_beach_01",
            "a_m_m_bevhills_01",
            "a_m_m_business_01",
            "a_m_m_eastsa_01",
            "a_m_m_farmer_01",
            "a_m_m_fatlatin_01",
            "a_m_m_genfat_01",
            "a_m_m_golfer_01",
            "a_m_m_hasjew_01",
            "a_m_m_hillbilly_01",
            "a_m_m_indian_01",
            "a_m_m_ktown_01",
            "a_m_m_malibu_01",
            "a_m_m_mexcntry_01",
            "a_m_m_mexlabor_01",
            "a_m_m_og_boss_01",
            "a_m_m_paparazzi_01",
            "a_m_m_polynesian_01",
            "a_m_m_prolhost_01",
            "a_m_m_rurmeth_01",
            "a_m_m_salton_01",
            "a_m_m_skater_01",
            "a_m_m_skidrow_01",
            "a_m_m_socenlat_01",
            "a_m_m_soucent_01",
            "a_m_m_stlat_02",
            "a_m_m_tennis_01",
            "a_m_m_tourist_01",
            "a_m_m_tramp_01",
            "a_m_m_trampbeac_01",
            "a_m_y_beach_01",
            "a_m_y_beachvesp_01",
            "a_m_y_bevhills_01",
            "a_m_y_business_01",
            "a_m_y_business_02",
            "a_m_y_business_03",
            "a_m_y_cyclist_01",
            "a_m_y_downtown_01",
            "a_m_y_eastsa_01",
            "a_m_y_epsilon_01",
            "a_m_y_gay_01",
            "a_m_y_genstreet_01",
            "a_m_y_golfer_01",
            "a_m_y_hippy_01",
            "a_m_y_hipster_01",
            "a_m_y_hipster_02",
            "a_m_y_ktown_01",
            "a_m_y_latino_01",
            "a_m_y_methhead_01",
            "a_m_y_mexthug_01",
            "a_m_y_motox_01",
            "a_m_y_musclbeac_01",
            "a_m_y_polynesian_01",
            "a_m_y_runner_01",
            "a_m_y_salton_01",
            "a_m_y_skater_01",
            "a_m_y_soucent_01",
            "a_m_y_stbla_01",
            "a_m_y_stlat_01",
            "a_m_y_stwhi_01",
            "a_m_y_sunbathe_01",
            "a_m_y_surfer_01",
            "a_m_y_vinewood_01",
            "a_m_y_yoga_01"
        ]
    },
    {
        "cat": "Femmes (civiles)",
        "icon": "👩",
        "items": [
            "a_f_m_beach_01",
            "a_f_m_bevhills_01",
            "a_f_m_business_02",
            "a_f_m_downtown_01",
            "a_f_m_eastsa_01",
            "a_f_m_fatbla_01",
            "a_f_m_fatwhite_01",
            "a_f_m_ktown_01",
            "a_f_m_prolhost_01",
            "a_f_m_salton_01",
            "a_f_m_skidrow_01",
            "a_f_m_soucent_01",
            "a_f_m_tourist_01",
            "a_f_m_tramp_01",
            "a_f_o_genstreet_01",
            "a_f_o_indian_01",
            "a_f_o_salton_01",
            "a_f_y_beach_01",
            "a_f_y_bevhills_01",
            "a_f_y_business_01",
            "a_f_y_business_02",
            "a_f_y_eastsa_01",
            "a_f_y_epsilon_01",
            "a_f_y_fitness_01",
            "a_f_y_genhot_01",
            "a_f_y_golfer_01",
            "a_f_y_hiker_01",
            "a_f_y_hippie_01",
            "a_f_y_hipster_01",
            "a_f_y_hipster_02",
            "a_f_y_indian_01",
            "a_f_y_juggalo_01",
            "a_f_y_runner_01",
            "a_f_y_rurmeth_01",
            "a_f_y_skater_01",
            "a_f_y_soucent_01",
            "a_f_y_tennis_01",
            "a_f_y_tourist_01",
            "a_f_y_vinewood_01",
            "a_f_y_yoga_01"
        ]
    },
    {
        "cat": "Gangs",
        "icon": "🕶️",
        "items": [
            "g_f_y_ballas_01",
            "g_f_y_families_01",
            "g_f_y_lost_01",
            "g_f_y_vagos_01",
            "g_m_m_armboss_01",
            "g_m_m_armgoon_01",
            "g_m_m_chiboss_01",
            "g_m_m_chigoon_01",
            "g_m_m_korboss_01",
            "g_m_m_mexboss_01",
            "g_m_m_mexboss_02",
            "g_m_y_armgoon_02",
            "g_m_y_azteca_01",
            "g_m_y_ballaeast_01",
            "g_m_y_ballaorig_01",
            "g_m_y_ballasout_01",
            "g_m_y_famca_01",
            "g_m_y_famdnf_01",
            "g_m_y_famfor_01",
            "g_m_y_korean_01",
            "g_m_y_korean_02",
            "g_m_y_lost_01",
            "g_m_y_lost_02",
            "g_m_y_lost_03",
            "g_m_y_mexgang_01",
            "g_m_y_mexgoon_01",
            "g_m_y_mexgoon_02",
            "g_m_y_mexgoon_03",
            "g_m_y_pologoon_01",
            "g_m_y_pologoon_02",
            "g_m_y_salvaboss_01",
            "g_m_y_salvagoon_01",
            "g_m_y_strpunk_01",
            "g_m_y_strpunk_02"
        ]
    },
    {
        "cat": "Métiers et commerces",
        "icon": "🧑‍🔧",
        "items": [
            "s_f_m_shop_high",
            "s_f_y_airhostess_01",
            "s_f_y_bartender_01",
            "s_f_y_scrubs_01",
            "s_f_y_shop_low",
            "s_f_y_shop_mid",
            "s_f_y_sweatshop_01",
            "s_m_m_ammucountry",
            "s_m_m_autoshop_01",
            "s_m_m_bouncer_01",
            "s_m_m_chemsec_01",
            "s_m_m_cntrybar_01",
            "s_m_m_dockwork_01",
            "s_m_m_doctor_01",
            "s_m_m_gaffer_01",
            "s_m_m_gardener_01",
            "s_m_m_hairdress_01",
            "s_m_m_highsec_01",
            "s_m_m_janitor",
            "s_m_m_lathandy_01",
            "s_m_m_lifeinvad_01",
            "s_m_m_linecook",
            "s_m_m_mariachi_01",
            "s_m_m_paramedic_01",
            "s_m_m_pilot_01",
            "s_m_m_postal_01",
            "s_m_m_scientist_01",
            "s_m_m_security_01",
            "s_m_m_strvend_01",
            "s_m_m_trucker_01",
            "s_m_m_ups_01",
            "s_m_o_busker_01",
            "s_m_y_airworker",
            "s_m_y_ammucity_01",
            "s_m_y_barman_01",
            "s_m_y_chef_01",
            "s_m_y_construct_01",
            "s_m_y_construct_02",
            "s_m_y_dealer_01",
            "s_m_y_doorman_01",
            "s_m_y_dwservice_01",
            "s_m_y_factory_01",
            "s_m_y_fireman_01",
            "s_m_y_garbage",
            "s_m_y_grip_01",
            "s_m_y_pestcont_01",
            "s_m_y_shop_mask",
            "s_m_y_valet_01",
            "s_m_y_waiter_01",
            "s_m_y_winclean_01",
            "s_m_y_xmech_01",
            "s_m_y_xmech_02"
        ]
    },
    {
        "cat": "Police, armée et prison",
        "icon": "👮",
        "items": [
            "s_f_y_cop_01",
            "s_f_y_ranger_01",
            "s_f_y_sheriff_01",
            "s_m_m_ciasec_01",
            "s_m_m_fiboffice_01",
            "s_m_m_fibsec_01",
            "s_m_m_marine_01",
            "s_m_m_marine_02",
            "s_m_m_prisguard_01",
            "s_m_m_snowcop_01",
            "s_m_y_armymech_01",
            "s_m_y_blackops_01",
            "s_m_y_blackops_02",
            "s_m_y_cop_01",
            "s_m_y_hwaycop_01",
            "s_m_y_marine_01",
            "s_m_y_marine_02",
            "s_m_y_marine_03",
            "s_m_y_prismuscl_01",
            "s_m_y_prisoner_01",
            "s_m_y_ranger_01",
            "s_m_y_sheriff_01",
            "s_m_y_swat_01",
            "s_m_y_uscg_01"
        ]
    },
    {
        "cat": "Personnages de l'histoire",
        "icon": "⭐",
        "items": [
            "ig_ballasog",
            "ig_beverly",
            "ig_chef",
            "ig_claypain",
            "ig_davenorton",
            "ig_devin",
            "ig_fbisuit_01",
            "ig_floyd",
            "ig_hao",
            "ig_jimmydisanto",
            "ig_josef",
            "ig_lamardavis",
            "ig_lazlow",
            "ig_lestercrest",
            "ig_mrk",
            "ig_nervousron",
            "ig_omega",
            "ig_oneil",
            "ig_ortega",
            "ig_paper",
            "ig_ramp_gang",
            "ig_siemonyetarian",
            "ig_solomon",
            "ig_stretch",
            "ig_taocheng",
            "ig_tenniscoach",
            "ig_tracydisanto",
            "ig_wade",
            "ig_zimbor",
            "player_one",
            "player_two",
            "player_zero"
        ]
    },
    {
        "cat": "Animaux",
        "icon": "🐕",
        "items": [
            "a_c_boar",
            "a_c_cat_01",
            "a_c_chickenhawk",
            "a_c_chimp",
            "a_c_chop",
            "a_c_cow",
            "a_c_coyote",
            "a_c_crow",
            "a_c_deer",
            "a_c_hen",
            "a_c_husky",
            "a_c_mtlion",
            "a_c_pig",
            "a_c_pigeon",
            "a_c_poodle",
            "a_c_pug",
            "a_c_rabbit_01",
            "a_c_rat",
            "a_c_retriever",
            "a_c_rhesus",
            "a_c_rottweiler",
            "a_c_seagull",
            "a_c_shepherd",
            "a_c_westy"
        ]
    }
],
};
